name: CICD

on:
    push:
        paths:
            - src/**    
        branches:
            - main
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - 
                name: Checkout repository
                uses: actions/checkout@v3

            - 
                name: Build Docker image
                run: |
                    docker build -t myperepo/python-app:${{ github.sha }} .

            - 
                name: Log in to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            - 
                name: Push Docker image
                run: |
                    echo "Tagging Docker image with short SHA..."
                    SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
                    echo "SHORT_SHA=${SHORT_SHA}"
                    echo "Tagging image: myperepo/python-app:${{ github.sha }} -> ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${SHORT_SHA}"
                    docker tag myperepo/python-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${SHORT_SHA}
                    echo "Pushing Docker image: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${SHORT_SHA}"
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${SHORT_SHA}
                    echo "Docker image pushed successfully."
        outputs:
            commit_id: $(echo "${GITHUB_SHA}" | cut -c1-6)



    CD:
        needs: ci
        runs-on: self-hosted

        steps:
            - 
                name: Checkout repository
                uses: actions/checkout@v3
            - 
                name: Modify values file
                run: |
                    echo ${{needs.ci.outputs.commit_id}}
                    pip install yq
                    yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml
            -
                name: Commit changes
                uses: EndBug/add-and-commit@v9
                with:
                    message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'
            - 
                name: Install argocd
                run: |
                    curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
                    chmod +x argocd
                    sudo mv ./argocd /usr/local/bin/argocd

            - 
                name: Argocd app sync
                run: |
                    argocd login argocd-server.argocd \
                     --username admin \
                     --password ${{ secrets.ARGOCD_ADMIN_PASSWORD }} \
                     --insecure \
                     --grpc-web
                    argocd app sync python-app --grpc-web
